### ISSUE TITLE
recur_on_mday(x, unless = )

### ISSUE THREAD

**Issue by Alternikaner** [DavisVaughan/almanac#77]
Hi Davis,

Firstly, thanks for the great package(s!).

Not sure if my issue is best addressed here, in vacation, or even if it's such an unusual requirement that it's not worth bothering with at all, but there it is anyway:  

I'm a South African, and our holidays only "carry over" to the next Monday if they fall on a Sunday - if it falls on a Saturday, the holiday is lost.

This can already be handled as follows:

``` r
library(almanac)

# Specify allowable days
nyd <- yearly() %>%
  recur_on_ymonth("Jan") %>%  
  recur_on_mday(1) %>% 
  recur_on_wday(c(1:5,7))

# Declare then intersect
newyearsday <- yearly() %>%
  recur_on_ymonth("Jan") %>%  
  recur_on_mday(1)

notsat <- weekly() %>% recur_on_wday(c(1:5,7))

nyd2 <- rintersect() %>% 
  add_rschedule(newyearsday) %>% 
  add_rschedule(notsat)

identical(alma_events(nyd) , alma_events(nyd2))
#> [1] TRUE
identical(nyd, nyd2)
#> [1] FALSE
```

<sup>Created on 2020-06-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

...but if it's a common enough pattern, perhaps something like
recur_on_mday(1, unless = "Sat")
might be worth implementing?

A variant of adj_following is another potential option, but I'm guessing you would prefer not to have one "adj_*" returning a different number of items than the rest.

**Comment by DavisVaughan** [comment]
Thanks! I would say that adding that argument to `recur_on_mday()` would be a bit too complicated. Internally it would force me to return a different data structure to account for the adjustment, which I wouldn't want to do.

That said, I think you can accomplish what you want with a `rsetdiff()` that removes Saturdays, followed up with an `radjusted()` that adjusts Sundays->Mondays

``` r
library(almanac)

hldys <- yearly() %>%
  recur_on_ymonth("Jan") %>%
  recur_on_mday(1)

# Set up days to remove
saturdays <- weekly() %>%
  recur_on_wday("Saturday")

cal <- rsetdiff() %>%
  add_rschedule(hldys) %>%
  add_rschedule(saturdays)

# 2005-01-01 is not present
alma_search("2000-01-01", "2007-01-01", cal)
#> [1] "2001-01-01" "2002-01-01" "2003-01-01" "2004-01-01" "2006-01-01"
#> [6] "2007-01-01"

# Ensure that was a saturday
lubridate::wday("2005-01-01", label = TRUE)
#> [1] Sat
#> Levels: Sun < Mon < Tue < Wed < Thu < Fri < Sat

# //////////////////////////////////////////////////////////////////////////////

# Also set up "rollover" for sunday -> monday
sundays <- weekly() %>%
  recur_on_wday("Sunday")

cal_adj <- radjusted(cal, adjust_on = sundays, adjustment = adj_following)

# Note that 2005-01-01 is not present
# Note that 2006-01-01 has been rolled forward
alma_search("2000-01-01", "2007-01-01", cal_adj)
#> [1] "2001-01-01" "2002-01-01" "2003-01-01" "2004-01-01" "2006-01-02"
#> [6] "2007-01-01"

# Check that it was a Sunday
lubridate::wday("2006-01-01", label = TRUE)
#> [1] Sun
#> Levels: Sun < Mon < Tue < Wed < Thu < Fri < Sat
```

<sup>Created on 2020-06-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Alternikaner** [comment]
Great, thanks!
